name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-setuptools \
          libffi-dev libssl-dev libltdl-dev zlib1g-dev openjdk-17-jdk \
          autoconf automake libtool pkg-config cmake

      - name: Install Buildozer
        run: |
          pip3 install --user --upgrade buildozer --break-system-packages
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
        env:
          USER: root

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
