name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          # هذا السطر هو الحل السحري لمشكلة بايثون 3.12
          command: pip install --user --upgrade buildozer --break-system-packages && buildozer android debug
        env:
          USER: root

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
