name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # هذا سيجعل GitHub يجد سيرفر فوراً
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-setuptools \
          libffi-dev libssl-dev libltdl-dev zlib1g-dev openjdk-17-jdk \
          autoconf automake libtool pkg-config cmake zip unzip

      - name: Install Buildozer and Cython
        run: |
          python3 -m pip install --upgrade pip
          # إجبار النظام على استخدام نسخة Cython المتوافقة لتجنب الخطأ السابق
          python3 -m pip install --user --upgrade buildozer "cython<3.0" --break-system-packages || python3 -m pip install --user --upgrade buildozer "cython<3.0"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        run: |
          yes | buildozer android debug
        env:
          USER: root

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ByWhats-WhatsApp-Style
          path: bin/*.apk
